### ISSUE TITLE
Use StructureDefinition for system in valueReferences

### ISSUE THREAD

**Issue by DavidPyke** [AudaciousInquiry/saner-ig#10]
For the valueReferences it is recommended that the system be structured as {"system":"http://hl7.org/fhir/R4/StructureDefinition", "code":"Observation.comment"}

Lloyd McKenzie: An element is typically expressed as Location.identifier, so including Location in the system is somewhat redundant.

Lloyd McKenzie: (We should use the element paths as the element identifier - given that that's what we do everywhere else)

**Comment by keithboone** [comment]
In progress...

**Comment by keithboone** [comment]
And following the discussion on Zulip, it's actually going to be more like {"system":"http://hl7.org/fhir/R4/StructureDefinition/Observation", "code":"Observation.note"}

Because 
1. http://hl7.org/fhir/R4/StructureDefinition/Observation#Observation.note actually resolves to something
2. That's the way it was done for Questionnaire
3. It the "redundancy" is only apparent b/c FHIR Observation is the StructureDefinition for the FHIR Observation resource.  We might actually use the StructureDefinition resources for the profiles in this guide.

**Comment by keithboone** [comment]
Done
