### ISSUE TITLE
Define a "Granular Availability Source" role

### ISSUE THREAD

**Issue by jmandel** [AudaciousInquiry/saner-ig#7]
Idea here is that rather than asking availability sources to maintain and update summary info, we should provide an onramp for granular reporting. For example, a "granular source" for bed information might POST and PUT information about specific Bed locations, marking individual beds as occupied or unoccupied -- and then a collector could pass these along, or could roll them up into summary `Group`s to provide an overview.

My goal here is to provide an "easy path" for bed management systems to just pass along granular data without requiring them to summarize everything; this allows for finer-grained decision-making downstream ("don't throw information away"), especially for operational decisions at the local/regional level. It also allows systems to summarize at any point in the pipeline, if they don't want to pass along individual bed-level information.

To flesh this out a bit: we can build an open source module that *generates* Group-level data on top of granular data, so a FHIR server can accept submissions in either format and ensure there's always up-to-to-date Group-level summaries available.

**Comment by jmandel** [comment]
(This issue is a placeholder for some discussion I'd like to have on our 3/25 check-in call.)

**Comment by keithboone** [comment]
Look at [ADT_A20](http://www.hl7.eu/refactored/dom01.html#tabs-35) for how this might come together, a routine bed status update, available e.g., from Epic inbound and outbound (meaning someone might tap into inbound feed, or use outbound feed) or other EHR system.

Key challenge is mapping bed identifier to data allowing classification.  

Many hospital masterfiles for beds don't classify the beds/locations except at department level because this is used for internal rather than external interop, staff already knows beds E100-E126 are in the ED.  Department codes are all over the map, and generally different at each hospital, even in same system.  I would look at this as a parallel track to follow that could track bed use and push aggregated data up to a system reporting to public health (which really wants numbers first, not to be the aggregator).

Definitely worthy of further discussion.  Based on our discussion Saturday, I have some thoughts around how to turn unclassified beds/departments into data that can be classified using standard vocabularies.  Might need some manual verification though.

**Comment by jmandel** [comment]
To be clear though: in order to enable Group-level reporting (in an automated way), won't these issues of bed/location mapping need to be addressed too? This is the part I'm missing; how do we get automated reporting at the Group level without having to do the "hard work" (non-scalable work) that we need to get automated reporting at the bed level?

**Comment by keithboone** [comment]
That's a question for Epic, Cerner, GEHC and others need to answer.

**Comment by jmandel** [comment]
Great -- it'd be good to include this in our agenda for tomorrow.
